### ISSUE TITLE
A general unexpected critical error has occured

### ISSUE THREAD

**Issue by imrecsoka** [vaklinov/hush-swing-wallet-ui#12]
Error: couldnt connect  to server : EOF reached (code 1)
make sure the server is running and you are connected to the right RPC port.
See the console output for more detailed error info.

Where is the dam console output?
What RPC port? what server? doesnt the wallet , or isnt it supposed to do that for you?

I generated this from the hush website:
# HUSH Configuaration File

# This file has been automatically generated by Hush Config Generator. It may be further customized by hand only.
# The rpcuser/rpcpassword are used for the local call to hushd. The rpcpassword was randomly set.
# Start Hush Configuration
daemon=1
server=1
rpcallowip=127.0.0.1
rpcuser=hushuser
rpcpassword=hushuser
datadir=H:\HushChain
gen=1
genproclimit=4
equihashsolver=tromp

What is missing?

**Comment by vaklinov** [comment]
The GUI wallet does not currently support changing/configuring the blockchain location to a non-default value. This is the likely reason for the problem.  More information about the problem may be found in log file %LOCALAPPDATA%\HUSHSwingWalletUI\HUSHWallet_2017_10_debug.log

**Comment by peacethroughmarketing** [comment]
this just happened to me while the wallet was running, had been running for 24 hours collecting mining revenue and now it won't launch no matter what and i had made no changes?

**Comment by peacethroughmarketing** [comment]
well legit, i re-wrote the config file and it is now working again

**Comment by project13et** [comment]
I have the same issue, The log file say

hushd is not runing at the moment or has not started/synchronized 100% - showing splash...
Splash: checking if hushd is already running...
Splash: hushd will be started...
java.io.IOException: error: couldn't connect to server: EOF reached (code 1)
(make sure server is running and you are connecting to the correct RPC port)
	at com.vaklinov.zcashui.ZCashClientCaller.getDaemonRawRuntimeInfo(ZCashClientCaller.java:172)
	at com.vaklinov.zcashui.StartupProgressDialog.waitForStartup(StartupProgressDialog.java:129)
	at com.vaklinov.zcashui.ZCashUI.main(ZCashUI.java:449)

How can I fix this issue ? Thanks,

**Comment by imrecsoka** [comment]
Sounds like a badly written wallet.

**Comment by vaklinov** [comment]
@imrecsoka The GUI wallet does not currently support changing/configuring the blockchain location to a non-default value. This is the likely reason for the problem. What you can do is use a default blockchain location... and other default parameters (rather than a custom `hush.conf`). The GUI wallet is not meant for mining (though it can be used in a mining contenxt).

@project13et It seems your HUSH daemon is not starting properly. The log file %APPDATA%\Hush\debug.log may reveal more information about the reason. You may also try to run `hushd.exe` manually before you start the GUI wallet.

**Comment by sh0ked** [comment]
Hi! the same issue on MacOS X El Capitan. I got this problem on Windows 10 after a few days  of good work. Later I move wallet.dat file to my macbook and got the same problem atfer full synchronization of wallet. 

```
➜  hush-wallet tail -n1000  ~/Library/Application\ Support/HUSHSwingWalletUI/HUSHWallet_2017_10_debug.log
Gathering of dashboard daemon status data done in 69ms.
Gathering of dashboard daemon status data done in 69ms.
Gathering of dashboard daemon status data done in 69ms.
Exiting ...
Stopping hushd because we started it - now it is alive: false
Stop command issued: error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)

hushd shut down successfully
=================================================================================
= New log started at: Sat Oct 28 22:51:57 NOVT 2017
=================================================================================

Starting HUSH Swing Wallet ...
OS: Mac OS X = MAC_OS
Current directory: /Users/sh0ked/hush-wallet
Class path: src/HUSHSwingWalletUI.jar
Environment PATH: /Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Applications/Postgres.app/Contents/Versions/latest/bin
Available look and feel: Metal javax.swing.plaf.metal.MetalLookAndFeel
Available look and feel: Nimbus javax.swing.plaf.nimbus.NimbusLookAndFeel
Using HUSH utilities: hushd: /Users/sh0ked/hush-wallet/hushd, hush-cli: /Users/sh0ked/hush-wallet/hush-cli
hushd is not runing at the moment or has not started/synchronized 100% - showing splash...
Splash: checking if hushd is already running...
Splash: hushd will be started...
java.io.IOException: error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)
	at com.vaklinov.zcashui.ZCashClientCaller.getDaemonRawRuntimeInfo(ZCashClientCaller.java:172)
	at com.vaklinov.zcashui.StartupProgressDialog.waitForStartup(StartupProgressDialog.java:129)
	at com.vaklinov.zcashui.ZCashUI.main(ZCashUI.java:449)
```

...and hush log.

```
➜  hush-wallet tail -n100  ~/Library/Application\ Support/Hush/debug.log
2017-10-28 15:51:59 Zcash version v1.0.9-307a1ca-dirty (2017-06-16 12:38:23 -0700)
2017-10-28 15:51:59 Using OpenSSL version OpenSSL 1.1.0d  26 Jan 2017
2017-10-28 15:51:59 Using BerkeleyDB version Berkeley DB 6.2.23: (March 28, 2016)
2017-10-28 15:51:59 Default data directory /Users/sh0ked/Library/Application Support/Hush
2017-10-28 15:51:59 Using data directory /Users/sh0ked/Library/Application Support/Hush
2017-10-28 15:51:59 Using config file /Users/sh0ked/Library/Application Support/Hush/hush.conf
2017-10-28 15:51:59 Using at most 125 connections (10240 file descriptors available)
2017-10-28 15:51:59 Using 4 threads for script verification
2017-10-28 15:51:59 scheduler thread start
2017-10-28 15:51:59 Loading verifying key from /Users/sh0ked/Library/Application Support/ZcashParams/sprout-verifying.key
2017-10-28 15:51:59 Loaded verifying key in 0.004413s seconds.
2017-10-28 15:51:59 HTTP: creating work queue of depth 16
2017-10-28 15:51:59 HTTP: starting 4 worker threads
2017-10-28 15:51:59 Using wallet wallet.dat
2017-10-28 15:51:59 init message: Verifying wallet...
2017-10-28 15:51:59 CDBEnv::Open: LogDir=/Users/sh0ked/Library/Application Support/Hush/database ErrorFile=/Users/sh0ked/Library/Application Support/Hush/db.log
2017-10-28 15:51:59 Bound to [::]:8888
2017-10-28 15:51:59 Bound to 0.0.0.0:8888
2017-10-28 15:51:59 Cache configuration:
2017-10-28 15:51:59 * Using 2.0MiB for block index database
2017-10-28 15:51:59 * Using 32.5MiB for chain state database
2017-10-28 15:51:59 * Using 65.5MiB for in-memory UTXO set
2017-10-28 15:51:59 init message: Loading block index...
2017-10-28 15:51:59 Opening LevelDB in /Users/sh0ked/Library/Application Support/Hush/blocks/index
2017-10-28 15:52:00 Opened LevelDB successfully
2017-10-28 15:52:00 Opening LevelDB in /Users/sh0ked/Library/Application Support/Hush/chainstate
2017-10-28 15:52:00 Opened LevelDB successfully
2017-10-28 15:52:05 LoadBlockIndexDB: last block file = 5
2017-10-28 15:52:05 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=16649, size=98688554, heights=176303...193098, time=2017-09-25...2017-10-25)
2017-10-28 15:52:05 Checking all blk files are present...
2017-10-28 15:52:05 LoadBlockIndexDB: transaction index disabled
2017-10-28 15:52:05 LoadBlockIndexDB: hashBestChain=0000000476d2ff2e25a535cf7ffe81de5fd71d5825ed85d253b6c7017da1b50d height=193076 date=2017-10-25 01:39:03 progress=0.993369
2017-10-28 15:52:05 *** This version has been deprecated as of block height 193076. You should upgrade to the latest version of Zcash. To disable deprecation for this version, set -disabledeprecation=1.0.9.
2017-10-28 15:52:05 Error: This version has been deprecated as of block height 193076. You should upgrade to the latest version of Zcash. To disable deprecation for this version, set -disabledeprecation=1.0.9.
2017-10-28 15:52:05 init message: Verifying blocks...
2017-10-28 15:52:05 Verifying last 288 blocks at level 3
2017-10-28 15:52:05 Shutdown requested. Exiting.
2017-10-28 15:52:05 Shutdown: In progress...
2017-10-28 15:52:05 StopRPC: waiting for async rpc workers to stop
```

Maybe problem in this error?

```
2017-10-28 15:52:05 Error: This version has been deprecated as of block height 193076. You should upgrade to the latest version of Zcash. To disable deprecation for this version, set -disabledeprecation=1.0.9.
```

How I can fix it?

**Comment by sh0ked** [comment]
Actually, set disabledeprecation=1.0.9 in hush.conf fixed this problem for me!

**Comment by daviddeket** [comment]
Hello,
so Í'm having the same problem with my wallet and do not know what to do. Please help...

Here is the log:

Starting HUSH Swing Wallet ...
OS: Windows 10 = WINDOWS
Current directory: C:\Users\david\Desktop\Desktop2\COINs\HUSH
Class path: C:\Users\david\Desktop\Desktop2\COINs\HUSH\HUSHSwingWalletUI.jar
Environment PATH: C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Users\david\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\david\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\david\AppData\Local\Programs\Python\Python36-32\
Using HUSH utilities: hushd: C:\Users\david\Desktop\Desktop2\COINs\HUSH\hushd.exe, hush-cli: C:\Users\david\Desktop\Desktop2\COINs\HUSH\hush-cli.exe
hushd is not runing at the moment or has not started/synchronized 100% - showing splash...
Splash: checking if hushd is already running...
Splash: hushd will be started...
java.io.IOException: error: couldn't connect to server: EOF reached (code 1)
(make sure server is running and you are connecting to the correct RPC port)
	at com.vaklinov.zcashui.ZCashClientCaller.getDaemonRawRuntimeInfo(ZCashClientCaller.java:172)
	at com.vaklinov.zcashui.StartupProgressDialog.waitForStartup(StartupProgressDialog.java:129)
	at com.vaklinov.zcashui.ZCashUI.main(ZCashUI.java:449)

I do not know much about wallets, so please, if you know how to fix it, explain it simple.
Thanks!

**Comment by vaklinov** [comment]
@daviddeket The HUSH 1.0.9 runtime version contained in the wallet release 0.68.6 has expired (refuses to run by default after a certain period of time). The best thing you can do is to go the HUSH website https://myhush.org/ and use the GUI wallet downloaded from there.

As @sh0ked mentioned, this can also be fixed by setting disabledeprecation=1.0.9 in the hush.conf file (in directory %APPDATA%/Hush).

**Comment by imrecsoka** [comment]
HI Vaklinov,
Thanks for explaining:
@imrecsoka The GUI wallet does not currently support changing/configuring the blockchain location to a non-default value. This is the likely reason for the problem. What you can do is use a default blockchain location... and other default parameters (rather than a custom hush.conf). The GUI wallet is not meant for mining (though it can be used in a mining contenxt).@project13et It seems your HUSH daemon is not starting properly. The log file %APPDATA%\Hush\debug.log may reveal more information about the reason. You may also try to run hushd.exe manually before you start the GUI wallet.

Will a solo mining option be available some time?
Or do we have to use pool solo mining?
I have no problems running my wallet version though, luckily.
I have asked for the block-chain to go to my D: drive for example, in the .conf file i think i specified that.
Hope it would be possible to solo mine some time.

**Comment by nbspencer** [comment]
@vaklinov i had the same problem on the version 0.68.6 : https://puu.sh/ye98n/c21832d229.png
So i tried what you said by installing the new wallet on the website but when i try to launch it i have this message : https://puu.sh/ye9a0/f1b0605326.png
What happens ?

**Comment by vaklinov** [comment]
@nbspencer The wallet you downloaded from https://myhush.org/  is not currently supported by me. You need to contact the other HUSH developers... Looking at the error I think the problem may be that you have 32-bit Windows (64-bit OS is required).

**Comment by nbspencer** [comment]
@vaklinov oh okey. I have 64 bit OS : 
![image](https://user-images.githubusercontent.com/18530808/32461207-629aaa80-c335-11e7-8e51-08718fa5c0bc.png)

**Comment by madbuda** [comment]
This is not a wallet issue, the hush binaries have auto depreciation and will not run

You can get the latest hush wallet from our website 
https://myhush.org/#tools
