### ISSUE TITLE
Error starting client

### ISSUE THREAD

**Issue by Hushminer9000** [vaklinov/hush-swing-wallet-ui#2]
zcashd is not runing at the moment or has not started/synchronized 100% - showing splash...
Splash: checking if zcashd is already running...
unexpected daemon info: Error reading configuration file: Missing zcash.conf

Splash: zcashd already running...
unexpected daemon info: Error reading configuration file: Missing zcash.conf

unexpected daemon info: Error reading configuration file: Missing zcash.conf

unexpected daemon info: Error reading configuration file: Missing zcash.conf

unexpected daemon info: Error reading configuration file: Missing zcash.conf

unexpected daemon info: Error reading configuration file: Missing zcash.conf

java.io.IOException: com.eclipsesource.json.ParseException: Expected value at 1:1
	at com.vaklinov.zcashui.ZCashClientCaller.getDaemonRawRuntimeInfo(ZCashClientCaller.java:198)
	at com.vaklinov.zcashui.StartupProgressDialog.waitForStartup(StartupProgressDialog.java:129)
	at com.vaklinov.zcashui.ZCashUI.main(ZCashUI.java:447)
Caused by: com.eclipsesource.json.ParseException: Expected value at 1:1
	at com.eclipsesource.json.JsonParser.error(JsonParser.java:490)
	at com.eclipsesource.json.JsonParser.expected(JsonParser.java:486)
	at com.eclipsesource.json.JsonParser.readValue(JsonParser.java:193)
	at com.eclipsesource.json.JsonParser.parse(JsonParser.java:152)
	at com.eclipsesource.json.JsonParser.parse(JsonParser.java:91)
	at com.eclipsesource.json.Json.parse(Json.java:295)
	at com.vaklinov.zcashui.ZCashClientCaller.getDaemonRawRuntimeInfo(ZCashClientCaller.java:194)
	... 2 more
Directory is named Zdash, i've tried files named both Zdash+ Zcash, both conf files. Running win 10 64-bit

**Comment by kal127** [comment]
Did you ever get a fix to this? I'm having the same problem.
