### ISSUE TITLE
Fail to initialize Hush Wallet

### ISSUE THREAD

**Issue by kal127** [vaklinov/hush-swing-wallet-ui#4]
Hi,

I've tried to initialize the hush wallet on my computer. I believe that I set up the configuration file correctly and in the correct location. I get the following error in the log after I run HUSHSwingWalletUI.

=================================================================================
= New log started at: Sun Jun 25 12:23:57 EDT 2017
=================================================================================

Starting HUSH Swing Wallet ...
OS: Windows 10 = WINDOWS
Current directory: C:\Users\K\Desktop\HUSHSwingWalletUI-Win32-native
Class path: C:\Users\K\Desktop\HUSHSwingWalletUI-Win32-native\HUSHSwingWalletUI.jar
Environment PATH: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Geth;C:\Users\K\AppData\Local\Microsoft\WindowsApps;
Using HUSH utilities: zcashd: C:\Users\K\Desktop\HUSHSwingWalletUI-Win32-native\zcashd.exe, zcash-cli: C:\Users\K\Desktop\HUSHSwingWalletUI-Win32-native\zcash-cli.exe
zcashd is not runing at the moment or has not started/synchronized 100% - showing splash...
Splash: checking if zcashd is already running...
unexpected daemon info: Error reading configuration file: Missing zcash.conf

Splash: zcashd already running...
unexpected daemon info: Error reading configuration file: Missing zcash.conf

unexpected daemon info: Error reading configuration file: Missing zcash.conf

unexpected daemon info: Error reading configuration file: Missing zcash.conf

unexpected daemon info: Error reading configuration file: Missing zcash.conf

unexpected daemon info: Error reading configuration file: Missing zcash.conf

java.io.IOException: com.eclipsesource.json.ParseException: Expected value at 1:1
	at com.vaklinov.zcashui.ZCashClientCaller.getDaemonRawRuntimeInfo(ZCashClientCaller.java:198)
	at com.vaklinov.zcashui.StartupProgressDialog.waitForStartup(StartupProgressDialog.java:129)
	at com.vaklinov.zcashui.ZCashUI.main(ZCashUI.java:447)
Caused by: com.eclipsesource.json.ParseException: Expected value at 1:1
	at com.eclipsesource.json.JsonParser.error(JsonParser.java:490)
	at com.eclipsesource.json.JsonParser.expected(JsonParser.java:486)
	at com.eclipsesource.json.JsonParser.readValue(JsonParser.java:193)
	at com.eclipsesource.json.JsonParser.parse(JsonParser.java:152)
	at com.eclipsesource.json.JsonParser.parse(JsonParser.java:91)
	at com.eclipsesource.json.Json.parse(Json.java:295)
	at com.vaklinov.zcashui.ZCashClientCaller.getDaemonRawRuntimeInfo(ZCashClientCaller.java:194)
	... 2 more

**Comment by vaklinov** [comment]
It appears you are using this release:
https://github.com/vaklinov/hush-swing-wallet-ui/releases/tag/0.68.3-beta
it is not the latest but should work. I think you did not create the zdash.conf file properly. Make sure it is named `zdash.conf` and not `zdash.txt` or similar:

STEP 3:    Create directory %APPDATA%\Zdash and a text file zdash.conf in it with the following content:
```
rpcuser=username
rpcpassword=SomePassword_PleaseChangeThisValue   
```
Step 3 must be performed or the GUI wallet will not work! The Windows environment variable %APPDATA% typically points to C:\Users\Your_Windows_User_Name\AppData\Roaming, so if your Windows user-name is Joe, the full directory to create may be C:\Users\Joe\AppData\Roaming\Zdash. To find out where %APPDATA% is, open a Windows explorer and type %APPDATA% in its file location box... Future versions of the GUI wallet installer will do this automatically.

**Comment by jaketeresi** [comment]
I'm having the same issue.

Starting HUSH Swing Wallet ...
OS: Windows 10 = WINDOWS
Current directory: C:\Users\jake\Desktop\Hush\HUSHSwingWalletUI-Win32-native
Class path: C:\Users\jake\Desktop\Hush\HUSHSwingWalletUI-Win32-native\HUSHSwingWalletUI.jar
Environment PATH: c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\microsoft sql server\client sdk\odbc\130\tools\binn\;c:\program files (x86)\microsoft sql server\130\tools\binn\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files\microsoft sql server\130\dts\binn\;c:\program files (x86)\microsoft sql server\client sdk\odbc\130\tools\binn\;c:\program files (x86)\microsoft sql server\140\tools\binn\;c:\program files (x86)\microsoft sql server\140\dts\binn\;c:\program files (x86)\microsoft sql server\140\tools\binn\managementstudio\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\jake\AppData\Local\Microsoft\WindowsApps;
Using HUSH utilities: zcashd: C:\Users\jake\Desktop\Hush\HUSHSwingWalletUI-Win32-native\zcashd.exe, zcash-cli: C:\Users\jake\Desktop\Hush\HUSHSwingWalletUI-Win32-native\zcash-cli.exe
zcashd is not runing at the moment or has not started/synchronized 100% - showing splash...
Splash: checking if zcashd is already running...
unexpected daemon info: Error reading configuration file: Missing zcash.conf

Splash: zcashd already running...
unexpected daemon info: Error reading configuration file: Missing zcash.conf

unexpected daemon info: Error reading configuration file: Missing zcash.conf

unexpected daemon info: Error reading configuration file: Missing zcash.conf

unexpected daemon info: Error reading configuration file: Missing zcash.conf

unexpected daemon info: Error reading configuration file: Missing zcash.conf

java.io.IOException: com.eclipsesource.json.ParseException: Expected value at 1:1
	at com.vaklinov.zcashui.ZCashClientCaller.getDaemonRawRuntimeInfo(ZCashClientCaller.java:198)
	at com.vaklinov.zcashui.StartupProgressDialog.waitForStartup(StartupProgressDialog.java:129)
	at com.vaklinov.zcashui.ZCashUI.main(ZCashUI.java:447)
Caused by: com.eclipsesource.json.ParseException: Expected value at 1:1
	at com.eclipsesource.json.JsonParser.error(JsonParser.java:490)
	at com.eclipsesource.json.JsonParser.expected(JsonParser.java:486)
	at com.eclipsesource.json.JsonParser.readValue(JsonParser.java:193)
	at com.eclipsesource.json.JsonParser.parse(JsonParser.java:152)
	at com.eclipsesource.json.JsonParser.parse(JsonParser.java:91)
	at com.eclipsesource.json.Json.parse(Json.java:295)
	at com.vaklinov.zcashui.ZCashClientCaller.getDaemonRawRuntimeInfo(ZCashClientCaller.java:194)
	... 2 more

I have a Zdash folder setup with zdash.conf and the provided text pasted in there.

**Comment by supajo** [comment]
FYI; Zdash.conf must be placed under %APPDATA%\Roaming\Zdash and not under %APPDATA%\Zdash 
The information provided here:"https://github.com/vaklinov/hush-swing-wallet-ui/releases/tag/0.68.3-beta" is wrong. Greetings Patrick

**Comment by jaketeresi** [comment]
I apologize, I had it in Roaming at first and I was having the same issue so I moved it to %APPDATA%. I finally moved it back and tried again and it still cannot find the directory.

**Comment by vaklinov** [comment]
Let me try to clarify again: `%APPDATA%` is a Windows environment variable. To achieve effective user confusion Microsoft has made this environment variable have value like `C:\Users\Your_Windows_User_Name\AppData\Roaming`. For user @jaketeresi the value is probably `C:\Users\jake\AppData\Roaming`. So the configuration file `%APPDATA%\Zdash\zdash.conf` actually has full path like `C:\Users\jake\AppData\Roaming\Zdash\zdash.conf`.

So to solve the problems of @kal127  and @jaketeresi (and @supajo if you have the same issue). Everyone: please open a windows command prompt (cmd.exe) and type the command:
```
dir %APPDATA%\Zdash
```
and paste the output here. I expect the command listing to show some sort of wrong naming of the file `%APPDATA%\Zdash\zdash.conf`.

Finally: we have a new release that does not require creating any files manually:
https://github.com/vaklinov/hush-swing-wallet-ui/blob/master/docs/Release_0.68.6.md
You may use it if the issue is not resolved after following my advice...
